
token = "mytoken"

drop_channels = [
  357651359379750917
]

cooldown_time = 20  # seconds for cooldown

recovery_time = 10  # seconds for probability to recover after cooldown expires

drop_chance = 0.1  # chance for drop per message as float (0.1 is 10%, etc)

additional_delay = 10  # time where extra coins can be gotten

admin_users = [
  122122926760656896,
  69198249432449024
]

# a list of guild IDs to pull static emotes from
emoji_sources = [
  272885620769161216,
  356869031870988309,
  356876866952364032,
  356876897403011072,
  396144014128054275,
  494946907181809667
]

drop_strings = [
  "I found this blob, but I can't remember what it's called! What was it?",
  "blobCAPTCHA v3: Please prove you're not a robot. What is the name of this blob?",
  "I dropped my glasses. What's the name of this blob?",
  "Blob located on main deck! Identification required *IMMEDIATELY*.",
  "I found this blob on the street! Can anyone tell me what type it is?",
  "My blob shirt got the print washed out! Tell me which one this is, so I can buy another one!"
]

[reward_roles]
# Roles given to users once they reach a certain coin threshold
100 = 518188361547120640

[currency]
singular = "<:blobcoin:386630453224013824> **Blob Coin**"
plural = "<:blobcoin:386630453224013824> **Blob Coins**"

[database]
# The keyword arguments that get passed into database connectors.
# If you're using the docker-compose, you do not need to change this.
host = "db"
port = 5432
user = "postgres"
password = ""
database = ""
max_size = 20
timeout = 60
