
token: "mytoken"

drop_channels:
  - 357651359379750917

cooldown_time: 20  # seconds for cooldown

recovery_time: 10  # seconds for probability to recover after cooldown expires

drop_chance: 0.1  # chance for drop per message as float (0.1 is 10%, etc)

db_credentials:
  host: localhost
  port: 5432
  user: myuser
  database: mydb
  password: "mypassword"
  timeout: 60

currency:
  singular: "<:blobcoin:386630453224013824> **Blob Coin**"
  plural: "<:blobcoin:386630453224013824> **Blob Coins**"

