
token: "mytoken"

drop_channels:
  - 357651359379750917

cooldown_time: 20  # seconds for cooldown

recovery_time: 10  # seconds for probability to recover after cooldown expires

drop_chance: 0.1  # chance for drop per message as float (0.1 is 10%, etc)

db_credentials:
  host: localhost
  port: 5432
  user: myuser
  database: mydb
  password: "mypassword"
  timeout: 60

currency:
  singular: "<:blobcoin:386630453224013824> **Blob Coin**"
  plural: "<:blobcoin:386630453224013824> **Blob Coins**"

admin_users:
  - 122122926760656896
  - 69198249432449024

emoji_sources:  # a list of guild IDs to pull static emotes from
  - 272885620769161216
  - 356869031870988309
  - 356876866952364032
  - 356876897403011072
  - 396144014128054275
  - 494946907181809667

drop_strings:
  - "I found this blob, but I can't remember what it's called! What was it?"
